### ISSUE TITLE
Global-Define branching strategy

### ISSUE THREAD

**Issue by cristiam86** [yeagerai/genlayer-simulator#278]

**Comment by cristiam86** [comment]
We agreed on having the following types of branches:
- main
- releases
- staging
- issue

We work on issue branches.
When the work is done, a PR is opened agains staging.
When the PR is tested and approved. It gets merged into staging.
(it isn't fine, but staging can be broken from time to time, when this happens, we should fix it ASAP)
Every Wednesday a release branch is going to be created from staging and a PR will be opened against main. The title of the PR is the release version.
If the release is tested and it works properly, the PR is merged and a production release is created. In the best case, it gets merged on Thursday, worst case, next Monday/Tuesday.

**Comment by AgustinRamiroDiaz** [comment]
@cristiam86 sounds good!

I'd also clarify that:
- for PRs:
  - the PR creator/owner is the one who merges the PR
- for release branches:
  - they can be branched from any commit from staging (so we can discard new features if needed)
  - they can cherrypick from staging (not recommended since it's usually a mess, but may be needed to incorporate features or hotfixes)
